export default {
  _meta: {
    description: "Demon's Souls armor pieces.",
    source:
      'https://github.com/Wulf2k/DeS-SaveEdit (VB source), http://demonssouls.wikidot.com/ (wiki)',
    schema:
      'Keyed by hex ID. Each entry has { name, type } and optionally { durability, note }. type is [type_id, sub_type_id] where sub_type_ids start from 0 (0 is reserved for Experimental). durability is an optional integer (max durability); present on player-obtainable pieces, absent on empty slots and NPC equipment. note is an optional wikidot-sourced summary with armor set name and player-interest details.',
  },
  items: {
    '0x186A0': {
      name: 'Gold Mask',
      type: [5, 1],
      durability: 150,
      note: "Rogue's set (Female Only). Phys 2/2/2/2, Magic 8, Fire 8, Bleed 16, Poison 16, Disease 16. Weight 0.6. Very low physical defense but high status resistances. Dropped by Mephistopheles or found in 3-2. Can be traded to Sparkly the Crow for a Colorless Demon's Soul.",
    },
    '0x18704': {
      name: 'Silver Coronet',
      type: [5, 1],
      durability: 100,
      note: "Wizard's set (Unisex). Phys 2/2/2/2, Magic 2, Fire 2. Weight 0.9. A decorative crown given to magicians of the Yormedar family — uniquely increases the user's maximum MP. Starting equipment of the Magician and Royalty classes.",
    },
    '0x18768': {
      name: "Assassin's Mask",
      type: [5, 1],
      durability: 300,
      note: "Assassin's set (Unisex). Phys 10/10/10/10, Magic 8, Fire 7, Poison 24. Weight 0.5. Part of a lightweight stealth set with high poison resistance. Starting equipment of the Thief class; also found in 3-1 Tower of Latria.",
    },
    '0x187CC': {
      name: 'Leather Cap',
      type: [5, 1],
      durability: 400,
      note: "Leather set (Unisex). Phys 11/11/11/11, Magic 8, Fire 8. Weight 1.2. Light hunter's headgear. Starting equipment of the Hunter and Wanderer classes. Sold by Graverobber Blige.",
    },
    '0x18830': {
      name: 'Chain Helmet',
      type: [5, 1],
      durability: 300,
      note: 'Chain set (Unisex). Phys 13/13/16.9/10.4, Magic 8, Fire 9. Weight 3.8. Strong against slash attacks; worn by soldiers of the church. Starting equipment of the Priest class. Sold by the Filthy Woman in 5-x.',
    },
    '0x18894': {
      name: 'Mirdan Helmet',
      type: [5, 1],
      durability: 200,
      note: 'Mirdan set (Unisex). Phys 14/14/17.5/14, Magic 9, Fire 12. Weight 5.4. White metal helm of temple knights. Good fire defense for its weight. Starting equipment of the Temple Knight class.',
    },
    '0x188F8': {
      name: 'Plate Helmet',
      type: [5, 1],
      durability: 300,
      note: 'Plate set (Unisex). Phys 13/13/16.3/13, Magic 8, Fire 9. Weight 3.8. Simple iron helmet common among soldiers. Starting equipment of the Soldier class. Sold by the Dregling Merchant.',
    },
    '0x1895C': {
      name: 'Fluted Helmet',
      type: [5, 1],
      durability: 250,
      note: 'Fluted set (Unisex). Phys 14/14/17.5/14, Magic 8, Fire 10. Weight 4.6. Iron helmet with grooves that enhance protection. Starting equipment of the Knight class; also found in 3-1 Tower of Latria.',
    },
    '0x189C0': {
      name: 'Brushwood Helmet',
      type: [5, 1],
      durability: 600,
      note: 'Brushwood set (Unisex). Phys 17/17/21.3/17, Magic 8, Fire 14. Weight 6.9, Stam Pen 3. Excellent fire resistance. Worn by Biorr of the Twin Fangs. Dropped by Biorr or found in 1-1 near Executioner Miralda (requires PWWT or PBWT).',
    },
    '0x18A24': {
      name: 'Dark Silver Helmet',
      type: [5, 1],
      durability: 550,
      note: 'Dark Silver set (Male Only). Phys 14/14/17.5/14, Magic 11, Fire 10. Weight 5.4. Dark silver helm from Vinland — said to exorcise malice. High magic defense. Dropped by Garl Vinland in 5-3.',
    },
    '0x18A88': {
      name: 'Gloom Helmet',
      type: [5, 1],
      durability: 450,
      note: 'Gloom set (Unisex). Phys 13/13/16.3/13, Magic 8, Fire 9, Bleed 18, Poison 18, Disease 18. Weight 4.6. Black iron helm with high status resistances. Worn by Yurt the Silent Chief. Dropped by Yurt.',
    },
    '0x18AEC': {
      name: "Ancient King's Mask",
      type: [5, 1],
      durability: 800,
      note: "Ancient King's set (Male Only). Phys 12/12/15/12, Magic 9, Fire 13. Weight 3.1. Bronze mask of the demigod Old King Doran with jewels inlaid. Excellent fire resistance with low stamina penalty. Dropped by Old King Doran in 1-1.",
    },
    '0x18C18': {
      name: "Venerable Sage's Hood",
      type: [5, 1],
      durability: 500,
      note: "Venerable Sage's set (Male Only). Phys 11/13.2/11/11, Magic 9, Fire 8. Weight 1.5. Travel wear of Sage Freke — plain but lightweight. Dropped by Sage Freke or found in 3-1 Tower of Latria.",
    },
    '0x18D44': {
      name: 'Bare Head',
      type: [5, 1],
      note: 'Empty head slot. Equipping nothing in the head slot provides no defensive bonuses.',
    },
    '0x18DA8': {
      name: "Official's Cap",
      type: [5, 1],
      durability: 50,
      note: "Official's set (Unisex, Unique). Phys 5/5/5/5, Magic 8, Fire 3. Weight 0.5. A unique cap with low defense. No other pieces in this set.",
    },
    '0x18E0C': {
      name: 'Dull Gold Helmet',
      type: [5, 1],
      durability: 550,
      note: "Dull Gold set (Female Only). Phys 13/13/16.3/13, Magic 11, Fire 9. Weight 3.8. Also known as Beggar's Helmet. War gear of high-ranking women in the highlands. Dropped by Selen Vinland or Phosphorescent Slugs.",
    },
    '0x18E70': {
      name: 'Binded Hood',
      type: [5, 1],
      durability: 300,
      note: 'Binded set (Female Only). Phys 12/12/12/12, Magic 8, Fire 11. Weight 2.3. Pointed hood worn by executioners. Good fire defense for its weight. Dropped by Executioner Miralda.',
    },
    '0x18ED4': {
      name: 'Three-Cornered Hat',
      type: [5, 1],
      durability: 300,
      note: "Witch's/Yuria's set (Female Only). Phys 10/12/10/10, Magic 9, Fire 5, Disease 24. Weight 1.4. A witch's hat with high disease resistance. Found in 3-1 Tower of Latria (requires Pure White World Tendency).",
    },
    '0x2BF20': {
      name: "Monk's Head Wrappings",
      type: [5, 1],
      durability: 0,
      note: "Monk's set (Unisex, Unique). Phys 2/2/2/2, Magic 0, Fire 2. Weight 0.0. Also known as Monk's Head Collar. Unique piece with negligible weight and stats — no other pieces in this set.",
    },
    '0x2E630': {
      name: 'Roaming Wizard (Cap)',
      type: [5, 1],
      note: 'NPC equipment. Headpiece worn by roaming NPC wizards. Not part of any player-obtainable armor set.',
    },
    '0x2E694': {
      name: 'Roaming Hunter (Cap)',
      type: [5, 1],
      note: 'NPC equipment. Headpiece worn by roaming NPC hunters. Not part of any player-obtainable armor set.',
    },
    '0x2E6F8': {
      name: 'Roaming Cleric (Cap)',
      type: [5, 1],
      note: 'NPC equipment. Headpiece worn by roaming NPC clerics. Not part of any player-obtainable armor set.',
    },
    '0x2E75C': {
      name: 'Roaming Warrior (Cap)',
      type: [5, 1],
      note: 'NPC equipment. Headpiece worn by roaming NPC warriors. Not part of any player-obtainable armor set.',
    },
    '0x30D40': {
      name: "Shaman's Clothes",
      type: [5, 2],
      durability: 300,
      note: "Shaman's set (Male Only). Phys 25/25/25/25, Magic 19, Fire 17. Weight 1.5. Very light chestpiece with decent defense. Heretical shaman's clothes with foul-smelling tallow. Found in 5-2 Leechmonger Archstone.",
    },
    '0x30DA4': {
      name: "Wizard's Clothes",
      type: [5, 2],
      durability: 350,
      note: "Wizard's set (Unisex). Phys 26/26/26/26, Magic 19, Fire 18. Weight 1.9. Lightweight mage chestpiece with good magic defense for its weight. Starting equipment of the Magician and Royalty classes. Found in 3-1 Tower of Latria.",
    },
    '0x30E08': {
      name: 'Black Leather',
      type: [5, 2],
      durability: 350,
      note: "Assassin's set (Unisex). Phys 25/25/25/25, Magic 19, Fire 17, Poison 62. Weight 1.2. Exceptional poison resistance and very light. Starting equipment of the Thief class; also found in 3-1 Tower of Latria.",
    },
    '0x30E6C': {
      name: 'Leather Armor',
      type: [5, 2],
      durability: 400,
      note: "Leather set (Unisex). Phys 28/28/28/28, Magic 19, Fire 20. Weight 3.1. Versatile hunter's armor with balanced stats. Starting equipment of the Hunter and Wanderer classes. Sold by Graverobber Blige.",
    },
    '0x30ED0': {
      name: 'Chain Mail',
      type: [5, 2],
      durability: 300,
      note: 'Chain set (Unisex). Phys 32/32/38.4/32, Magic 19, Fire 22. Weight 9.6. Strong against slash attacks; worn by warriors of the church. Starting equipment of the Priest class. Sold by the Filthy Woman.',
    },
    '0x30F34': {
      name: 'Mirdan Scale Mail',
      type: [5, 2],
      durability: 200,
      note: 'Mirdan set (Unisex). Phys 36/36/43.2/36, Magic 21, Fire 32. Weight 13.5. Scale mail of temple knights with excellent fire defense. Starting equipment of the Temple Knight class.',
    },
    '0x30F98': {
      name: 'Coat of Plate',
      type: [5, 2],
      durability: 300,
      note: "Plate set (Unisex). Phys 32/32/38.4/32, Magic 19, Fire 22. Weight 9.6. Common soldier's iron chestpiece. Starting equipment of the Soldier class. Sold by the Dregling Merchant.",
    },
    '0x30FFC': {
      name: 'Fluted Armor',
      type: [5, 2],
      durability: 250,
      note: 'Fluted set (Unisex). Phys 34/34/40.7/34, Magic 19, Fire 24. Weight 11.5. Grooved iron armor that enhances protection. Starting equipment of the Knight class; also found in 3-1 Tower of Latria.',
    },
    '0x31060': {
      name: 'Brushwood Armor',
      type: [5, 2],
      durability: 600,
      note: 'Brushwood set (Unisex). Phys 42/42/50.4/42, Magic 19, Fire 31. Weight 17.3, Stam Pen 5 (severe). The heaviest chestpiece in the game with the highest physical defense. Excellent fire resistance but severely impedes stamina regeneration. Worn by Biorr.',
    },
    '0x310C4': {
      name: 'Dark Silver Armor',
      type: [5, 2],
      durability: 550,
      note: 'Dark Silver set (Male Only). Phys 36/36/43.2/36, Magic 27, Fire 25. Weight 13.5. Exceptional magic defense — the highest among heavy chestpieces. Dark silver is said to exorcise malice. Dropped by Garl Vinland.',
    },
    '0x31128': {
      name: 'Gloom Armor',
      type: [5, 2],
      durability: 450,
      note: 'Gloom set (Unisex). Phys 34/34/40.8/34, Magic 19, Fire 24, Bleed 46, Poison 46, Disease 46. Weight 11.5. Outstanding all-around status resistance — the best for bleed, poison, and disease. Worn by Yurt the Silent Chief. Dropped by Yurt.',
    },
    '0x3118C': {
      name: "Ancient King's Breastplate",
      type: [5, 2],
      durability: 800,
      note: "Ancient King's/Plate set (Male Only). Phys 31/31/37.2/31, Magic 21, Fire 34. Weight 7.1. Bronze breastplate of Old King Doran with jewels inlaid. Exceptional fire defense and only 1/5 stamina penalty despite its protection. Can be used with the Plate set.",
    },
    '0x311F0': {
      name: "Saint's Robe",
      type: [5, 2],
      durability: 450,
      note: "Saint's set (Male Only). Phys 27/32.4/27/27, Magic 23, Fire 16. Weight 4.6. High magic defense for a lightweight robe. Worn by Saint Urbain. Dropped by Saint Urbain or found in 5-1 Valley of Defilement.",
    },
    '0x312B8': {
      name: "Venerable Sage's Robe",
      type: [5, 2],
      durability: 500,
      note: "Venerable Sage's set (Male Only). Phys 27/32.4/27/27, Magic 23, Fire 19. Weight 3.8. Lightweight traveling robe with strong magic defense. Worn by Sage Freke. Dropped by Sage Freke or found in 3-1 Tower of Latria.",
    },
    '0x313E4': {
      name: 'Bare Chest',
      type: [5, 2],
      note: 'Empty chest slot. Equipping nothing in the chest slot provides no defensive bonuses.',
    },
    '0x31448': {
      name: "Rogue's Clothes",
      type: [5, 2],
      durability: 150,
      note: "Rogue's set (Female Only). Phys 25/25/25/25, Magic 25, Fire 17. Weight 1.5. Luxurious vest woven with gold thread. Very high magic defense for its extremely low weight. Found in 3-1 Tower of Latria.",
    },
    '0x314AC': {
      name: 'Dull Gold Armor',
      type: [5, 2],
      durability: 550,
      note: "Dull Gold set (Female Only). Phys 32/32/38.4/32, Magic 27, Fire 22. Weight 9.6. Also known as Beggar's Armor. High magic defense. Dropped by Selen Vinland or Phosphorescent Slugs.",
    },
    '0x31510': {
      name: 'Binded Cross',
      type: [5, 2],
      durability: 300,
      note: "Binded set (Female Only). Phys 29/29/29/29, Magic 19, Fire 26. Weight 5.8. Executioner's armor with excellent fire defense and only 1/5 stamina penalty. Dropped by Executioner Miralda.",
    },
    '0x31574': {
      name: 'Old Ragged Robes',
      type: [5, 2],
      durability: 300,
      note: "Witch's/Yuria's set (Female Only). Phys 26/31.2/26/26, Magic 23, Fire 13, Poison 62. Weight 3.5. Ragged robes with exceptional poison resistance and high magic defense. Found in 1-1 Boletarian Palace. Despite the description, stats are strong.",
    },
    '0x46CD0': {
      name: 'Roaming Wizard (Chest)',
      type: [5, 2],
      note: 'NPC equipment. Chestpiece worn by roaming NPC wizards. Not part of any player-obtainable armor set.',
    },
    '0x46D34': {
      name: 'Roaming Hunter (Chest)',
      type: [5, 2],
      note: 'NPC equipment. Chestpiece worn by roaming NPC hunters. Not part of any player-obtainable armor set.',
    },
    '0x46D98': {
      name: 'Roaming Cleric (Chest)',
      type: [5, 2],
      note: 'NPC equipment. Chestpiece worn by roaming NPC clerics. Not part of any player-obtainable armor set.',
    },
    '0x46DFC': {
      name: 'Roaming Warrior (Chest)',
      type: [5, 2],
      note: 'NPC equipment. Chestpiece worn by roaming NPC warriors. Not part of any player-obtainable armor set.',
    },
    '0x493E0': {
      name: "Shaman's Armbands",
      type: [5, 3],
      durability: 300,
      note: "Shaman's set (Male Only). Phys 15/15/15/15, Magic 12, Fire 10. Weight 0.9. Very light arm wrappings. Found in 5-2 Leechmonger Archstone.",
    },
    '0x49444': {
      name: "Wizard's Gloves",
      type: [5, 3],
      durability: 350,
      note: "Wizard's set (Unisex). Phys 16/16/16/16, Magic 12, Fire 11. Weight 1.2. Lightweight gloves with balanced defense. Starting equipment of the Magician and Royalty classes. Found in 3-1 Tower of Latria.",
    },
    '0x494A8': {
      name: 'Black Gloves',
      type: [5, 3],
      durability: 300,
      note: "Assassin's set (Unisex). Phys 15/15/15/15, Magic 12, Fire 10, Poison 37. Weight 0.7. Very light gloves with strong poison resistance. Starting equipment of the Thief class; also found in 3-1 Tower of Latria.",
    },
    '0x4950C': {
      name: 'Leather Gloves',
      type: [5, 3],
      durability: 400,
      note: "Leather set (Unisex). Phys 17/17/17/17, Magic 12, Fire 12. Weight 1.8. Versatile hunter's gloves. Starting equipment of the Hunter and Wanderer classes. Sold by Graverobber Blige.",
    },
    '0x49570': {
      name: 'Chain Gloves',
      type: [5, 3],
      durability: 300,
      note: 'Chain set (Unisex). Phys 20/20/26/16, Magic 12, Fire 14. Weight 5.8. Strong against slash attacks. Starting equipment of the Priest class. Sold by the Filthy Woman.',
    },
    '0x495D4': {
      name: 'Mirdan Gauntlets',
      type: [5, 3],
      durability: 200,
      note: 'Mirdan set (Unisex). Phys 22/22/26.4/22, Magic 13, Fire 20. Weight 8.1. White metal gauntlets of temple knights with excellent fire defense. Starting equipment of the Temple Knight class.',
    },
    '0x49638': {
      name: 'Plate Gauntlets',
      type: [5, 3],
      durability: 300,
      note: "Plate set (Unisex). Phys 20/20/24/20, Magic 12, Fire 14. Weight 5.8. Common soldier's iron gauntlets. Starting equipment of the Soldier class. Sold by the Dregling Merchant.",
    },
    '0x4969C': {
      name: 'Fluted Gauntlets',
      type: [5, 3],
      durability: 250,
      note: 'Fluted set (Unisex). Phys 21/21/25.3/21, Magic 12, Fire 15. Weight 6.9. Grooved iron gauntlets that enhance protection. Starting equipment of the Knight class; also found in 3-1 Tower of Latria.',
    },
    '0x49700': {
      name: 'Brushwood Gauntlets',
      type: [5, 3],
      durability: 600,
      note: 'Brushwood set (Unisex). Phys 25/25/30/25, Magic 12, Fire 19. Weight 10.4, Stam Pen 3. Also known as Brushwood Manifer. Excellent fire resistance but heavy. Worn by Biorr.',
    },
    '0x49764': {
      name: 'Dark Silver Gauntlets',
      type: [5, 3],
      durability: 550,
      note: 'Dark Silver set (Male Only). Phys 20/20/24/20, Magic 16, Fire 14. Weight 8.1. Also known as Dark Silver Manifer. High magic defense. Dropped by Garl Vinland.',
    },
    '0x497C8': {
      name: 'Gloom Gauntlets',
      type: [5, 3],
      durability: 450,
      note: 'Gloom set (Unisex). Phys 20/20/24/20, Magic 12, Fire 14, Bleed 28, Poison 28, Disease 28. Weight 6.9. High status resistances across the board. Worn by Yurt the Silent Chief.',
    },
    '0x4982C': {
      name: "Ancient King's Gauntlets",
      type: [5, 3],
      durability: 800,
      note: "Ancient King's set (Male Only). Phys 19/19/22.8/19, Magic 13, Fire 21. Weight 4.6. Bronze gauntlets of Old King Doran. Outstanding fire defense with minimal stamina penalty (1/5). Dropped by Old King Doran.",
    },
    '0x49890': {
      name: "Saint's Gloves",
      type: [5, 3],
      durability: 450,
      note: "Saint's set (Male Only). Phys 16/19.2/16/16, Magic 14, Fire 9. Weight 2.8. Lightweight gloves with strong magic defense. Dropped by Saint Urbain or found in 5-1 Valley of Defilement.",
    },
    '0x49958': {
      name: "Venerable Sage's Gloves",
      type: [5, 3],
      durability: 500,
      note: "Venerable Sage's set (Male Only). Phys 16/19.2/16/16, Magic 14, Fire 11. Weight 2.3. Lightweight traveling gloves with good magic defense. Dropped by Sage Freke or found in 3-1 Tower of Latria.",
    },
    '0x499BC': {
      name: 'Bare Hands',
      type: [5, 3],
      note: 'Empty arms slot. Equipping nothing in the arms slot provides no defensive bonuses.',
    },
    '0x49A84': {
      name: 'Silver Bracelets',
      type: [5, 3],
      durability: 100,
      note: 'Silver Bracelets (Female Only, Unique). Phys 2/2/2/2, Magic 2, Fire 2. Weight 0.5. Unique arm piece with minimal defense. Stacks with Ring of Avarice and Soul Thirst for bonus souls.',
    },
    '0x49AE8': {
      name: "Rogue's Gloves",
      type: [5, 3],
      durability: 150,
      note: "Rogue's set (Female Only). Phys 15/15/15/15, Magic 15, Fire 10. Weight 0.9. Luxurious gloves with gold thread. High magic defense for extremely low weight. Found in 3-1 Tower of Latria.",
    },
    '0x49B4C': {
      name: 'Dull Gold Gauntlets',
      type: [5, 3],
      durability: 550,
      note: 'Dull Gold set (Female Only). Phys 19/19/22.8/19, Magic 16, Fire 13. Weight 5.8. Also known as Dull Gold Manifer. Good magic defense. Dropped by Selen Vinland or Phosphorescent Slugs.',
    },
    '0x49BB0': {
      name: 'Binded Gloves',
      type: [5, 3],
      durability: 300,
      note: "Binded set (Female Only). Phys 17/17/17/17, Magic 12, Fire 15. Weight 3.5. Executioner's gauntlets with good fire defense and minimal stamina penalty (1/5). Dropped by Executioner Miralda.",
    },
    '0x49C14': {
      name: 'Old Ragged Gloves',
      type: [5, 3],
      durability: 300,
      note: "Witch's/Yuria's set (Female Only). Phys 16/19.2/16/16, Magic 14, Fire 8, Poison 37. Weight 2.1. Ragged gloves with strong poison resistance and good magic defense. Found in 1-1 Boletarian Palace.",
    },
    '0x5F370': {
      name: 'Roaming Wizard (Gloves)',
      type: [5, 3],
      note: 'NPC equipment. Gloves worn by roaming NPC wizards. Not part of any player-obtainable armor set.',
    },
    '0x5F3D4': {
      name: 'Roaming Hunter (Gloves)',
      type: [5, 3],
      note: 'NPC equipment. Gloves worn by roaming NPC hunters. Not part of any player-obtainable armor set.',
    },
    '0x5F438': {
      name: 'Roaming Cleric (Gloves)',
      type: [5, 3],
      note: 'NPC equipment. Gloves worn by roaming NPC clerics. Not part of any player-obtainable armor set.',
    },
    '0x5F49C': {
      name: 'Roaming Warrior (Gloves)',
      type: [5, 3],
      note: 'NPC equipment. Gloves worn by roaming NPC warriors. Not part of any player-obtainable armor set.',
    },
    '0x61A80': {
      name: "Shaman's Tabi",
      type: [5, 4],
      durability: 300,
      note: "Shaman's set (Male Only). Phys 15/15/15/15, Magic 12, Fire 10. Weight 0.9. Also known as Shaman's Tabi Socks. Very light leggings. Found in 5-2 Leechmonger Archstone.",
    },
    '0x61AE4': {
      name: "Wizard's Shoes",
      type: [5, 4],
      durability: 350,
      note: "Wizard's set (Unisex). Phys 16/16/16/16, Magic 12, Fire 11. Weight 1.2. Lightweight shoes with balanced defense. Starting equipment of the Magician and Royalty classes. Found in 3-1 Tower of Latria.",
    },
    '0x61B48': {
      name: 'Black Boots',
      type: [5, 4],
      durability: 350,
      note: "Assassin's set (Unisex). Phys 15/15/15/15, Magic 12, Fire 10, Poison 37. Weight 0.7. Very light boots that muffle footsteps with strong poison resistance. Starting equipment of the Thief class; also found in 3-1 Tower of Latria.",
    },
    '0x61BAC': {
      name: 'Leather Boots',
      type: [5, 4],
      durability: 450,
      note: "Leather set (Unisex). Phys 17/17/17/17, Magic 12, Fire 12. Weight 1.8. Versatile hunter's boots. Starting equipment of the Hunter and Wanderer classes. Sold by Graverobber Blige.",
    },
    '0x61C10': {
      name: 'Hard Leather Boots',
      type: [5, 4],
      durability: 300,
      note: 'Chain set (Unisex). Phys 20/20/26/16, Magic 12, Fire 14. Weight 5.8. Strong against slash attacks; widely worn by soldiers of the church. Starting equipment of the Priest class. Sold by the Filthy Woman.',
    },
    '0x61C74': {
      name: 'Mirdan Leggings',
      type: [5, 4],
      durability: 200,
      note: 'Mirdan set (Unisex). Phys 22/22/26.4/22, Magic 13, Fire 20. Weight 8.1. White metal greaves of temple knights with excellent fire defense. Starting equipment of the Temple Knight class.',
    },
    '0x61CD8': {
      name: 'Plate Leggings',
      type: [5, 4],
      durability: 300,
      note: "Plate set (Unisex). Phys 20/20/24/20, Magic 12, Fire 14. Weight 5.8. Common soldier's iron greaves. Starting equipment of the Soldier class. Sold by the Dregling Merchant.",
    },
    '0x61D3C': {
      name: 'Fluted Leggings',
      type: [5, 4],
      durability: 250,
      note: 'Fluted set (Unisex). Phys 21/21/25.3/21, Magic 12, Fire 15. Weight 6.9. Grooved iron greaves that enhance protection. Starting equipment of the Knight class; also found in 3-1 Tower of Latria.',
    },
    '0x61DA0': {
      name: 'Brushwood Leggings',
      type: [5, 4],
      durability: 600,
      note: 'Brushwood set (Unisex). Phys 25/25/30/25, Magic 12, Fire 19. Weight 10.4, Stam Pen 3. Excellent fire resistance but heavy. Worn by Biorr of the Twin Fangs.',
    },
    '0x61E04': {
      name: 'Dark Silver Leggings',
      type: [5, 4],
      durability: 550,
      note: 'Dark Silver set (Male Only). Phys 20/20/24/20, Magic 16, Fire 14. Weight 8.1. High magic defense. Dark silver from Vinland is said to exorcise malice. Dropped by Garl Vinland.',
    },
    '0x61E68': {
      name: 'Gloom Leggings',
      type: [5, 4],
      durability: 450,
      note: 'Gloom set (Unisex). Phys 20/20/24/20, Magic 12, Fire 14, Bleed 28, Poison 28, Disease 28. Weight 6.9. High status resistances across the board. Worn by Yurt the Silent Chief.',
    },
    '0x61ECC': {
      name: "Ancient King's Leggings",
      type: [5, 4],
      durability: 800,
      note: "Ancient King's set (Male Only). Phys 19/19/22.8/19, Magic 13, Fire 21. Weight 4.6. Bronze greaves of Old King Doran. Outstanding fire defense with minimal stamina penalty (1/5). Dropped by Old King Doran.",
    },
    '0x61F30': {
      name: "Saint's Boots",
      type: [5, 4],
      durability: 450,
      note: "Saint's set (Male Only). Phys 16/19.2/16/16, Magic 14, Fire 9. Weight 2.8. Lightweight boots with good magic defense. Dropped by Saint Urbain or found in 5-1 Valley of Defilement.",
    },
    '0x61FF8': {
      name: "Venerable Sage's Boots",
      type: [5, 4],
      durability: 500,
      note: "Venerable Sage's set (Male Only). Phys 16/19.2/16/16, Magic 14, Fire 11. Weight 2.3. Lightweight traveling boots with good magic defense. Dropped by Sage Freke or found in 3-1 Tower of Latria.",
    },
    '0x6205C': {
      name: 'Bare Legs',
      type: [5, 4],
      note: 'Empty legs slot. Equipping nothing in the legs slot provides no defensive bonuses.',
    },
    '0x62188': {
      name: "Rogue's Boots",
      type: [5, 4],
      durability: 150,
      note: "Rogue's set (Female Only). Phys 15/15/15/15, Magic 15, Fire 10. Weight 0.9. Luxurious boots with gold thread. High magic defense for extremely low weight. Found in 3-1 Tower of Latria.",
    },
    '0x621EC': {
      name: 'Dull Gold Leggings',
      type: [5, 4],
      durability: 550,
      note: "Dull Gold set (Female Only). Phys 19/19/22.8/19, Magic 16, Fire 13. Weight 5.8. Also known as Dull Gold/Beggar's Leggings. Good magic defense. Dropped by Selen Vinland or Phosphorescent Slugs.",
    },
    '0x62250': {
      name: 'Binded Boots',
      type: [5, 4],
      durability: 300,
      note: "Binded set (Female Only). Phys 17/17/17/17, Magic 12, Fire 15. Weight 3.5. Executioner's boots with good fire defense and minimal stamina penalty (1/5). Dropped by Executioner Miralda.",
    },
    '0x622B4': {
      name: 'Old Ragged Boots',
      type: [5, 4],
      durability: 300,
      note: "Witch's/Yuria's set (Female Only). Phys 16/19.2/16/16, Magic 14, Fire 8, Poison 37. Weight 2.1. Ragged boots with strong poison resistance and good magic defense. Found in 1-1 Boletarian Palace.",
    },
    '0x77A10': {
      name: 'Roaming Wizard (Leggings)',
      type: [5, 4],
      note: 'NPC equipment. Leggings worn by roaming NPC wizards. Not part of any player-obtainable armor set.',
    },
    '0x77A74': {
      name: 'Roaming Hunter (Leggings)',
      type: [5, 4],
      note: 'NPC equipment. Leggings worn by roaming NPC hunters. Not part of any player-obtainable armor set.',
    },
    '0x77AD8': {
      name: 'Roaming Cleric (Leggings)',
      type: [5, 4],
      note: 'NPC equipment. Leggings worn by roaming NPC clerics. Not part of any player-obtainable armor set.',
    },
    '0x77B3C': {
      name: 'Roaming Warrior (Leggings)',
      type: [5, 4],
      note: 'NPC equipment. Leggings worn by roaming NPC warriors. Not part of any player-obtainable armor set.',
    },
  },
};
