#!/usr/bin/env node
/**
 * tools/gen-version.mjs
 *
 * Single source of truth for the app version: reads `version` from
 * package.json and syncs it into every other version-bearing file:
 *   - js/version.js              (UI; full rewrite)
 *   - src-tauri/Cargo.toml       ([package] version)
 *   - src-tauri/tauri.conf.json  (version)
 *   - src-tauri/Cargo.lock       (root package version; no checksum)
 *   - package-lock.json          (two root demonsave-ps3 entries)
 *
 * Mirrors the generated-file convention of tools/gen-des-db-index.mjs.
 *
 * Usage:
 *   node tools/gen-version.mjs          # write all targets
 *   node tools/gen-version.mjs --check  # exit 1 if any target drifts
 *
 * @ts-check
 */

import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const version = JSON.parse(readFileSync(path.join(ROOT, 'package.json'), 'utf-8')).version;
if (!version || !/^\d+\.\d+\.\d+/.test(version)) {
  console.error(`✖ package.json has an invalid version: ${String(version)}`);
  process.exit(1);
}

const check = process.argv.includes('--check');

/**
 * @typedef {{ re: RegExp, replacement: string, expected: number }} Transform
 * @typedef {{ label: string, file: string, rewrite?: string, transform?: Transform }} Target
 */

/**
 * Replace within `content` using a global regex, requiring exactly
 * `expected` matches; throw otherwise so structural drift is loud.
 * @param {string} content
 * @param {RegExp} reGlobal  must include the `g` flag
 * @param {string} replacement
 * @param {number} expected
 * @returns {string}
 */
function applyTransform(content, reGlobal, replacement, expected) {
  const count = [...content.matchAll(reGlobal)].length;
  if (count !== expected) {
    throw new Error(
      `expected ${expected} match(es) for ${reGlobal.source}, found ${count}. File structure changed?`,
    );
  }
  return content.replace(reGlobal, replacement);
}

const versionJsContent =
  `// Generated by tools/gen-version.mjs from package.json; do not edit by hand.\n` +
  `export const APP_VERSION = '${version}';\n`;

/** @type {Target[]} */
const targets = [
  {
    label: 'js/version.js',
    file: path.join(ROOT, 'js', 'version.js'),
    rewrite: versionJsContent,
  },
  {
    label: 'src-tauri/Cargo.toml',
    file: path.join(ROOT, 'src-tauri', 'Cargo.toml'),
    transform: {
      re: /(name = "demonsave-ps3"\r?\nversion = ")[^"]*(")/g,
      replacement: `$1${version}$2`,
      expected: 1,
    },
  },
  {
    label: 'src-tauri/tauri.conf.json',
    file: path.join(ROOT, 'src-tauri', 'tauri.conf.json'),
    transform: {
      re: /("version": ")[^"]*(")/g,
      replacement: `$1${version}$2`,
      expected: 1,
    },
  },
  {
    label: 'src-tauri/Cargo.lock',
    file: path.join(ROOT, 'src-tauri', 'Cargo.lock'),
    transform: {
      re: /(name = "demonsave-ps3"\r?\nversion = ")[^"]*(")/g,
      replacement: `$1${version}$2`,
      expected: 1,
    },
  },
  {
    label: 'package-lock.json',
    file: path.join(ROOT, 'package-lock.json'),
    transform: {
      re: /("name": "demonsave-ps3",\r?\n\s*"version": ")[^"]*(")/g,
      replacement: `$1${version}$2`,
      expected: 2,
    },
  },
];

try {
  if (check) {
    const drifted = [];
    for (const t of targets) {
      let current;
      try {
        current = readFileSync(t.file, 'utf-8');
      } catch {
        drifted.push(`${t.label} (missing)`);
        continue;
      }
      try {
        if (t.rewrite !== undefined) {
          if (current !== t.rewrite) drifted.push(t.label);
        } else if (t.transform) {
          const next = applyTransform(
            current,
            t.transform.re,
            t.transform.replacement,
            t.transform.expected,
          );
          if (next !== current) drifted.push(t.label);
        }
      } catch (err) {
        drifted.push(`${t.label} (${err instanceof Error ? err.message : String(err)})`);
      }
    }
    if (drifted.length > 0) {
      console.error(
        `✖ version out of sync with package.json (v${version}) in:\n  - ${drifted.join('\n  - ')}`,
      );
      console.error('  Fix: npm run gen:version');
      process.exit(1);
    }
    console.log(`✓ all version targets in sync (v${version})`);
  } else {
    for (const t of targets) {
      let current;
      try {
        current = readFileSync(t.file, 'utf-8');
      } catch {
        if (t.rewrite !== undefined) {
          writeFileSync(t.file, t.rewrite);
          console.log(`✓ wrote ${t.label} (v${version})`);
          continue;
        }
        throw new Error(`${t.label} not found; cannot transform`);
      }
      let next;
      try {
        next =
          t.rewrite !== undefined
            ? t.rewrite
            : t.transform
              ? applyTransform(
                  current,
                  t.transform.re,
                  t.transform.replacement,
                  t.transform.expected,
                )
              : current;
      } catch (err) {
        const reason = err instanceof Error ? err.message : String(err);
        throw new Error(`${t.label}: ${reason}`, { cause: err });
      }
      if (next !== current) {
        writeFileSync(t.file, next);
        console.log(`✓ wrote ${t.label} (v${version})`);
      } else {
        console.log(`  ${t.label} already v${version}`);
      }
    }
    console.log(`\nDone. All targets at v${version}.`);
  }
} catch (err) {
  console.error(`✖ ${err instanceof Error ? err.message : String(err)}`);
  process.exit(1);
}
